### ISSUE TITLE
Doppel is unable to see teammates if a role has been copied

### ISSUE THREAD

**Issue by The1337Gh0st** [ZacharyHinds/ttt2-role-dop#9]
If the Doppel has copied the role of someone already, and if there is someone else that has the exact some role setup as them (e.g. an Unknown is killed by a Traitor Doppel), they will be unable to see the role of their teammate(s).

**Comment by ZacharyHinds** [comment]
Can you explain this in a little more detail? I am not sure what the exact issue is

**Comment by ZacharyHinds** [comment]
If you are referencing the fact that Doppelgangers cannot see other disguised Doppelgangers, then I have fixed that with the most recent [commit](https://github.com/ZacharyHinds/ttt2-role-dop/commit/4ac979f4cbe1d45b346b69b4490d4d72c12fc0d3). I'll close this for now, because unless there's something I am missing, I don't know what else you could be referring to.
